export const BASE_URL = import.meta.env.PUBLIC_ENV__BACKEND_URL;
export const ENDPOINT_AUTH_SIGNIN = import.meta.env
  .PUBLIC_ENV__ENDPOINT_AUTH_SIGNIN;
export const ENDPOINT_AUTH_SIGNOUT = import.meta.env
  .PUBLIC_ENV__ENDPOINT_AUTH_SIGNOUT;
export const ENDPOINT_AUTH_REFRESH = import.meta.env
  .PUBLIC_ENV__ENDPOINT_AUTH_REFRESH;
export const ENDPOINT_AUTH_MAINIMAGE = import.meta.env
  .PUBLIC_ENV__ENDPOINT_AUTH_MAINIMAGE;
export const ENDPOINT_AUTH_UPDATEIMAGE = import.meta.env
  .PUBLIC_ENV__ENDPOINT_AUTH_UPDATEIMAGE;
export const ENDPOINT_AUTH_UPDATEPASSWORD = import.meta.env
  .PUBLIC_ENV__ENDPOINT_AUTH_UPDATEPASSWORD;
export const ENDPOINT_WORKS = import.meta.env.PUBLIC_ENV__ENDPOINT_WORKS;
export const ENDPOINT_TOOLS = import.meta.env.PUBLIC_ENV__ENDPOINT_TOOLS;
export const ENDPOINT_CONTACTINFO = import.meta.env
  .PUBLIC_ENV__ENDPOINT_CONTACTINFO;
