export const constColors = {
  accent: "rgb(163, 0, 255)",
  blue: "#2222cc",
  green: "#27ae60",
  orange: "#ff7711",
  red: "#cc2222",
};

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    minHeight: "100vh",
    transition: "background-color 0.5s ease, color 0.5s ease",
    fontFamily: "Inter, sans-serif",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    padding: "1.5rem 5%",
    position: "sticky",
    width: "100%",
    top: 0,
    zIndex: 1000,
    boxSizing: "border-box",
    backdropFilter: "blur(10px)",
  },
  navLinks: { display: "flex", gap: "1.5rem", alignItems: "center" },
  logo: {
    cursor: "pointer",
    fontWeight: 900,
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  navLink: { textDecoration: "none", fontSize: "0.8rem", fontWeight: 600 },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "1.2rem",
  },
  languageBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "2rem",
    fontFamily: "tajawal",
  },
  select: {
    background: "none",
    border: "none",
    color: "inherit",
    fontWeight: "bold",
    cursor: "pointer",
  },
  contactBtn: {
    border: "none",
    padding: "0.5rem 1rem",
    fontWeight: 700,
    borderRadius: "4px",
    cursor: "pointer",
  },
  hero: {
    height: "80vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  visualStack: {
    display: "flex",
    gap: "3rem",
    marginBottom: "3rem",
    scale: "0.7",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  heroTitle: {
    textJustify: "inter-word",
    fontSize: "clamp(3rem, 10vw, 6rem)",
    fontWeight: 900,
    lineHeight: 1,
    margin: 0,
  },
  heroSub: {
    marginTop: "1.5rem",
    fontSize: "0.7rem",
    fontWeight: 700,
  },
  aboutSection: { padding: "10rem 10%" },
  imageContainer: {
    position: "relative",
    display: "flex",
  },
  aboutContent: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    justifyItems: "center",
    gap: "30px",
    minWidth: 0,
    width: "100%",
  },
  profileImg: {
    objectFit: "cover",
    borderRadius: "20px",
    zIndex: 2,
    minWidth: 0,
    width: "100%",
    maxWidth: "500px",
    minHeight: "300px",
  },
  sectionTitle: {
    fontSize: "2rem",
    fontWeight: 800,
    marginBottom: "1.5rem",
  },
  sectionTitleCenter: {
    width: "100%",
    textAlign: "center",
    fontSize: "2rem",
    fontWeight: 800,
    marginBottom: "1.5rem",
  },
  p: { textWrap: "wrap", lineHeight: 1.8, fontSize: "1.1rem" },
  footer: {
    padding: "4rem",
    textAlign: "center",
    fontSize: "0.8rem",
    opacity: 0.5,
  },

  workSection: {
    padding: "5rem 5%",
  },
  filterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: "4rem",
    flexWrap: "wrap",
    gap: "2rem",
  },
  filterGroup: { display: "flex", gap: "1rem" },
  filterBtn: {
    background: "none",
    border: "none",
    borderBottom: "2px solid",
    padding: "0.5rem 1rem",
    cursor: "pointer",
    fontWeight: 700,
    transition: "0.3s",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
    gap: "3rem",
  },
  cardImage: {
    height: "400px",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "12px",
    position: "relative",
    overflow: "hidden",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
  },
  tag: {
    background: "#fff",
    color: "#000",
    padding: "4px 12px",
    borderRadius: "50px",
    fontSize: "0.7rem",
    fontWeight: 900,
    position: "absolute",
    bottom: "20px",
    left: "20px",
  },
  cardTitle: { marginTop: "1.5rem", fontSize: "1.2rem", fontWeight: 700 },

  skeletonStyleContainer: {
    width: "100%",
    height: "400px",
    borderRadius: "12px",
    background: "#999",
    backgroundImage:
      "linear-gradient(to right, #999 0%, #edeef1 20%, #999 40%, #999 100%)",
    backgroundRepeat: "no-repeat",
    backgroundSize: "800px 400px",
    animation: "shimmer 1.5s infinite linear",
  },

  skeletonStyleTitle: {
    height: "20px",
    width: "70%",
    marginTop: "15px",
    borderRadius: "4px",
    background: "#f6f7f8",
    backgroundImage:
      "linear-gradient(to right, #999 0%, #edeef1 20%, #999 40%, #999 100%)",
    animation: "shimmer 1.5s infinite linear",
  },
  loginContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "85vh",
    flexDirection: "column",
  },
  loginBox: {
    padding: "2rem",
    background: "#fff",
    borderRadius: "8px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    textAlign: "center",
  },
  input: {
    display: "block",
    width: "100%",
    padding: "10px",
    marginBottom: "10px",
    border: "1px solid #ddd",
  },
  button: {
    borderRadius: "5px",
    margin: "20px",
    padding: "10px 20px",
    border: "none",
    cursor: "pointer",
  },
  dashboardLayout: {
    display: "flex",
    flexDirection: "column",
    height: "max(86dvh, 100%)",
  },
  sidebar: {
    padding: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  navBtn: {
    border: `1px solid ${constColors.accent}`,
    textAlign: "center",
    cursor: "pointer",
    padding: "10px",
  },
  activeNav: {
    backgroundColor: constColors.accent,
    border: `1px solid ${constColors.accent}`,
    color: "#fff",
    textAlign: "center",
    cursor: "pointer",
    padding: "10px",
    fontWeight: "bold",
  },
  main: { padding: "40px", width: "100%", maxWidth: "100%" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  table: {
    border: "1px solid #aaa",
    width: "100%",
    borderCollapse: "collapse",
    borderRadius: "8px",
    overflow: "hidden",
  },
  genericBtn: {
    padding: "10px 20px",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  deleteBtn: {
    color: "#e74c3c",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  logoutBtn: {
    marginTop: "auto",
    color: "#e74c3c",
    border: "none",
    background: "none",
    cursor: "pointer",
    textAlign: "left",
  },
  formTitle: {
    marginBottom: "20px",
  },
  errorPageContainer: {
    width: "100%",
    height: "85dvh",
    display: "flex",
    flexDirection: "column",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  errorPageCode: { marginBottom: "40px", scale: "5", fontWeight: "1000" },
  overlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    width: "100dvw",
    height: "100dvh",
  },
  fieldGroup: { marginBottom: "1rem" },
  label: {
    display: "block",
    marginBottom: "5px",
    fontWeight: "bold",
    fontSize: "14px",
  },
  formInput: {
    width: "100%",
    padding: "8px",
    border: "1px solid #ccc",
    borderRadius: "4px",
  },
  actions: {
    display: "flex",
    justifyContent: "center",
    gap: "10px",
    marginTop: "20px",
  },
  cancelBtn: {
    padding: "8px 16px",
    border: `1px solid ${constColors.accent}`,
    borderRadius: "4px",
    cursor: "pointer",
  },
  submitBtn: {
    padding: "8px 16px",
    backgroundColor: constColors.accent,
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
};
