export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    minHeight: "100vh",
    transition: "background-color 0.5s ease, color 0.5s ease",
    fontFamily: "Inter, sans-serif",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    padding: "1.5rem 5%",
    position: "sticky",
    width: "100%",
    top: 0,
    zIndex: 1000,
    boxSizing: "border-box",
    backdropFilter: "blur(10px)",
  },
  navLinks: { display: "flex", gap: "1.5rem", alignItems: "center" },
  logo: {
    cursor: "pointer",
    fontWeight: 900,
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  navLink: { textDecoration: "none", fontSize: "0.8rem", fontWeight: 600 },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "1.2rem",
  },
  languageBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "2rem",
    fontFamily: "tajawal",
  },
  select: {
    background: "none",
    border: "none",
    color: "inherit",
    fontWeight: "bold",
    cursor: "pointer",
  },
  contactBtn: {
    border: "none",
    padding: "0.5rem 1rem",
    fontWeight: 700,
    borderRadius: "4px",
    cursor: "pointer",
  },
  hero: {
    height: "80vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  visualStack: {
    display: "flex",
    gap: "3rem",
    marginBottom: "3rem",
    scale: "0.7",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  heroTitle: {
    textJustify: "inter-word",
    fontSize: "clamp(3rem, 10vw, 6rem)",
    fontWeight: 900,
    lineHeight: 1,
    margin: 0,
  },
  heroSub: {
    marginTop: "1.5rem",
    fontSize: "0.7rem",
    fontWeight: 700,
  },
  aboutSection: { padding: "10rem 10%" },
  aboutContent: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "4rem",
    alignItems: "center",
  },
  imageContainer: { position: "relative" },
  profileImg: {
    width: "100%",
    height: "400px",
    objectFit: "cover",
    borderRadius: "20px",
    zIndex: 2,
    position: "relative",
  },
  sectionTitle: {
    fontSize: "2rem",
    fontWeight: 800,
    marginBottom: "1.5rem",
  },
  sectionTitleCenter: {
    width: "100%",
    textAlign: "center",
    fontSize: "2rem",
    fontWeight: 800,
    marginBottom: "1.5rem",
  },
  p: { lineHeight: 1.8, fontSize: "1.1rem" },
  footer: {
    padding: "4rem",
    textAlign: "center",
    fontSize: "0.8rem",
    opacity: 0.5,
  },

  workSection: { padding: "5rem 5%" },
  filterHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: "4rem",
    flexWrap: "wrap",
    gap: "2rem",
  },
  filterGroup: { display: "flex", gap: "1rem" },
  filterBtn: {
    background: "none",
    border: "none",
    borderBottom: "2px solid",
    padding: "0.5rem 1rem",
    cursor: "pointer",
    fontWeight: 700,
    transition: "0.3s",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
    gap: "3rem",
  },
  cardImage: {
    height: "400px",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "12px",
    position: "relative",
    overflow: "hidden",
  },
  tag: {
    background: "#fff",
    color: "#000",
    padding: "4px 12px",
    borderRadius: "50px",
    fontSize: "0.7rem",
    fontWeight: 900,
    position: "absolute",
    bottom: "20px",
    left: "20px",
  },
  cardTitle: { marginTop: "1.5rem", fontSize: "1.2rem", fontWeight: 700 },

  skeletonStyleContainer: {
    width: "100%",
    height: "400px",
    borderRadius: "12px",
    background: "#999",
    backgroundImage:
      "linear-gradient(to right, #999 0%, #edeef1 20%, #999 40%, #999 100%)",
    backgroundRepeat: "no-repeat",
    backgroundSize: "800px 400px",
    animation: "shimmer 1.5s infinite linear",
  },

  skeletonStyleTitle: {
    height: "20px",
    width: "70%",
    marginTop: "15px",
    borderRadius: "4px",
    background: "#f6f7f8",
    backgroundImage:
      "linear-gradient(to right, #999 0%, #edeef1 20%, #999 40%, #999 100%)",
    animation: "shimmer 1.5s infinite linear",
  },
};
